// app/layout.tsx

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.scss';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import StickyBanner from '@/components/layout/StickyBanner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

  viewport: {
    width: 'device-width',
    initialScale: 1,
    viewportFit: 'cover',
  },

  formatDetection: {
    telephone: false,
    date: false,
    address: false,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="app-wrapper" style={{ overflowX: 'clip', width: '100%' }}>
          <Header />
          {children}
          <Footer />
          <StickyBanner />
        </div>
      </body>
    </html>
  );
}
